In [1]:
import cv2
import numpy as np

In [2]:
def generate_dataset():
    face_classifier = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
    def face_cropped(img):
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_classifier.detectMultiScale(gray, 1.3, 5)
    
        if faces == ():
            return None   
        for (x,y,w,h) in faces:
            cropped_face = img[y:y+h,x:x+w]
        return cropped_face
    
    cap = cv2.VideoCapture(0)
    img_id = 0
    
    while True:
        ret, frame = cap.read()
        if face_cropped(frame) is not None:
            img_id+=1
            face = cv2.resize(face_cropped(frame), (200,200))
            face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)
            file_name_path = "C:/Users/Asus/Desktop/dedrite/data/"+"harsh."+str(img_id)+".jpg"
            #file_name_path = "C:/Users/Asus/Desktop/dedrite/data/Images for visualization/"+str(img_id)+'.jpg'
            cv2.imwrite(file_name_path, face)
            cv2.putText(face, str(img_id), (50,50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2 )
            
            cv2.imshow("Cropped_Face", face)
            if cv2.waitKey(1)==13 or int(img_id)==40:
                break
                 
    cap.release()
    cv2.destroyAllWindows()
    print("Collecting samples is completed !!!")
generate_dataset()

C:\Users\Asus\AppData\Local\Temp/ipykernel_30960/3632878736.py:7: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if faces == ():


In [3]:
def my_label(image_name):
    name = image_name.split('.')[-3]
    if name=="harsh":
        return np.array([1,0,0])
    elif name=="ayush":
        return np.array([0,1,0])
    elif name=="disha":
        return np.array([0,0,1])

In [4]:
import os
from random import shuffle
from tqdm import tqdm

In [5]:
def my_data():
    data = []
    for img in tqdm(os.listdir("data")):
        path=os.path.join("data",img)
        img_data = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img_data = cv2.resize(img_data, (50,50))
        data.append([np.array(img_data), my_label(img)])
    shuffle(data) 
    
    return data

In [6]:
data = my_data()


100%|███████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 358.80it/s]


In [7]:
train = data[:70]  
test = data[70:]
X_train = np.array([i[0] for i in train]).reshape(-1,50,50,1)
print(X_train.shape)
y_train = [i[1] for i in train]
X_test = np.array([i[0] for i in test]).reshape(-1,50,50,1)
print(X_test.shape)
y_test = [i[1] for i in test]

(70, 50, 50, 1)
(30, 50, 50, 1)


In [9]:
print(X_test)

[[[[228]
   [230]
   [231]
   ...
   [226]
   [225]
   [225]]

  [[229]
   [229]
   [229]
   ...
   [226]
   [225]
   [225]]

  [[228]
   [229]
   [229]
   ...
   [225]
   [224]
   [225]]

  ...

  [[ 73]
   [ 68]
   [ 75]
   ...
   [ 57]
   [ 57]
   [ 59]]

  [[ 72]
   [ 73]
   [ 74]
   ...
   [ 56]
   [ 55]
   [ 55]]

  [[ 66]
   [ 72]
   [ 73]
   ...
   [ 52]
   [ 57]
   [ 55]]]


 [[[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  ...

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]]


 [[[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  ...

  [[  0]
   [  0]
   [  0]
   

In [ ]:
pip install tflearn

In [5]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: requests<3,>=2.21.0 in c:\users\asus\anaconda3\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (2.27.1)



In [12]:
# import warnings
# warnings.filterwarnings('ignore')

import tensorflow as tf
import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression

Instructions for updating:
non-resource variables are not supported in the long term
curses is not supported on this machine (please install/reinstall curses for an optimal experience)


In [13]:
#tf.reset_default_graph()
tf.compat.v1.reset_default_graph()
convnet = input_data(shape=[50,50,1])
convnet = conv_2d(convnet, 32, 5, activation='relu')
# 32 filters and stride=5 so that the filter will move 5 pixel or unit at a time
convnet = max_pool_2d(convnet, 5)
convnet = conv_2d(convnet, 64, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)
convnet = conv_2d(convnet, 128, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)
convnet = conv_2d(convnet, 64, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)
convnet = conv_2d(convnet, 32, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = fully_connected(convnet, 1024, activation='relu')
convnet = dropout(convnet, 0.8)
convnet = fully_connected(convnet, 3, activation='softmax')
convnet = regression(convnet, optimizer='adam', learning_rate = 0.001, loss='categorical_crossentropy')
model = tflearn.DNN(convnet, tensorboard_verbose=1)
model.fit(X_train, y_train, n_epoch=12, validation_set=(X_test, y_test), show_metric = True, run_id="FRS" )

Training Step: 23  | total loss: 1.09525 | time: 0.048s
| Adam | epoch: 012 | loss: 1.09525 - acc: 0.3540 -- iter: 64/70
Training Step: 24  | total loss: 1.11476 | time: 1.100s
| Adam | epoch: 012 | loss: 1.11476 - acc: 0.3013 | val_loss: 0.93364 - val_acc: 0.6333 -- iter: 70/70
--


In [ ]:
def data_for_visualization():
    Vdata = []
    for img in tqdm(os.listdir("Images for visualization")):
        path = os.path.join("Images for visualization", img)
        img_num = img.split('.')[0] 
        img_data = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img_data = cv2.resize(img_data, (50,50))
        Vdata.append([np.array(img_data), img_num])
    shuffle(Vdata)
    return Vdata

In [ ]:
Vdata = data_for_visualization()


In [ ]:
import matplotlib.pyplot as plt   # pip install matplotlib

fig = plt.figure(figsize=(20,20))
for num, data in enumerate(Vdata[:20]):
    img_data = data[0]
    y = fig.add_subplot(5,5, num+1)
    image = img_data
    data = img_data.reshape(50,50,1)
    model_out = model.predict([data])[0]
    
    if np.argmax(model_out) == 1:
        my_label = 'ayush'
    elif np.argmax(model_out) == 0:
        my_label = 'harsh'
    else:
        my_label = 'disha'
        
    y.imshow(image, cmap='gray')
    plt.title(my_label)
    
    y.axes.get_xaxis().set_visible(False)
    y.axes.get_yaxis().set_visible(False)
plt.show()

In [ ]:
!pip install -U efficientnet

In [2]:
# to import the crucial library
from keras import applications
# importing the model
from tensorflow.keras.applications import EfficientNetB4
# importing the call backs 
from keras import callbacks
# importing required layers
from keras.models import Sequential
# importing crucial layers
from keras.layers import Flatten,BatchNormalization,MaxPooling2D

In [3]:
from keras.layers.pooling import GlobalAveragePooling2D  
# importing layers 
from keras.layers import Dense
# to import the dense layer

efficient_net = EfficientNetB4(   # initializing the model efficientnet
    weights='imagenet',
    input_shape=(255,255,3), # defining the shape 
    include_top=False,
    pooling='max'
)

Efficient_Model = Sequential()
# defining the input layer
Efficient_Model.add(efficient_net)
# adding the dense layer
Efficient_Model.add(Dense(units = 5, activation='softmax'))
# last result layer of the algorithm efficient net
Efficient_Model.summary()
# to print the summary

71686520/71686520 [==============================] - 13s 0us/step
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 efficientnetb4 (Functional)  (None, 1792)             17673823  
                                                                 
 dense (Dense)               (None, 5)                 8965      
                                                                 
Total params: 17,682,788
Trainable params: 17,557,581
Non-trainable params: 125,207
_________________________________________________________________


In [6]:
# importing the optimizer and compiling the code
Efficient_Model.compile(loss=tf.keras.losses.CategoricalCrossentropy(), optimizer='adam', metrics=['Accuracy'])  # to compile the model

In [25]:
history = Efficient_Model.fit(  #  to trained the model 
    X_train, y_train,
    epochs =100,  # initializing the epochs 
        batch_size = 28,  # initializing the bs
    validation_data = (X_test, y_test))

ValueError: Calling `Model.fit` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.fit` with eager mode enabled.

In [27]:
# *VGG-16*

import keras,os
# importing library
from keras.models import Sequential
# importing basic required layers
from keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense, Activation,GlobalMaxPooling2D
# importing the model
from keras.models import Model
# importing the basic 
from keras import optimizers , layers, applications
#importing vgg16 model
from tensorflow.keras.applications import VGG16

#initializing the algorithm
vgg16 = VGG16(input_shape = (224,224,3),weights = "imagenet", include_top = False)

for layer in vgg16.layers:
  # making the trainable layer in vgg 19 as false.
    layer.trainable = False 

# defining the last layer
last_layer = vgg16.get_layer('block5_pool')
# to add the result layer
last_output = last_layer.output
# adding a layer to combined into fixed shape
x = GlobalMaxPooling2D()(last_output)
# Adding a hidden layer
x = Dense(512, activation='relu')(x)
# Adding a layer of dropout
x = Dropout(0.5)(x)
# adding an output layer
x = Dense(5, activation='softmax')(x)

vgg16_model1 = Model(vgg16.input, x) 
# initializing the model

 # to debug the algorithm
vgg16_model1.compile(loss='categorical_crossentropy',   
                # debugging the algorithm
             optimizer='Adam',
             # initializing the optimizer
              metrics=['accuracy'])

vgg16_model1.summary() # function to show the summary

#to trained the algorithm
history = vgg16_model1.fit(Flower_X_TRAIN,Flower_Y_TRAIN,
          epochs = 20, # defining the iterations 
          validation_data = (Flower_X_VAL,Flower_Y_VAL),
          batch_size = 32 )

# to import the c_r
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
# importing basic library of c_m
pred1 = vgg16_model1.predict(Flower_X_TEST)
# initializing predict variable
pred1_T = vgg16_model1.predict(Flower_X_TRAIN)


print(classification_report(np.argmax(Flower_Y_TEST, axis=1), np.argmax(pred1, axis=1))) 
print() # for testing score
print('Testing Accuracy : ', accuracy_score(np.argmax(Flower_Y_TEST, axis=1), np.argmax(pred1, axis=1)))
print() # for training score
print('Training Accuracy : ', accuracy_score(np.argmax(Flower_Y_TRAIN, axis=1), np.argmax(pred1_T, axis=1)))

# importing some important functions
from sklearn.metrics import precision_score,recall_score,f1_score
print('Precision by RF of testing data is: %.3f' % precision_score(np.argmax(Flower_Y_TEST, axis=1), np.argmax(pred1, axis=1),average='micro')) 
# checking the precision value
print('Recall by RF of testing data is: %.3f' % recall_score(np.argmax(Flower_Y_TEST, axis=1), np.argmax(pred1, axis=1),average='micro')) 
# checking the recall value
print('F1 score by RF of testing data is: %.3f' % f1_score(np.argmax(Flower_Y_TEST, axis=1), np.argmax(pred1, axis=1),average='micro')) 
# checking the f2 score

# importing cm
from sklearn.metrics import confusion_matrix 
# initializing the c_m
cm = confusion_matrix(np.argmax(y_test, axis=1), np.argmax(pred1, axis=1))

# plotting cm
import seaborn as sns
# assigning the shape 
plt.figure(figsize=(10,10))
# assigning heat map color
sns.heatmap(cm,annot=True,cmap=random.choice(cmap),  fmt='d')
# defining its x-axis name 
plt.xlabel('Predicted values')
# dfining its y-axis name
plt.ylabel('Original Values')

58889256/58889256 [==============================] - 12s 0us/step
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                             

NameError: name 'Flower_X_TRAIN' is not defined